name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up NDK
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25b
    - name: build freetype
      run: ndk-build NDK_PROJECT_PATH=./android/freetype
    - name: build expat
      run: ndk-build NDK_PROJECT_PATH=./android/expat
    - name: build
      run: ndk-build NDK_PROJECT_PATH=./android/
