name: MacOSX Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python3 Distutils
      run: |
        python -m pip install --upgrade pip setuptools wheel packaging
    - name: gen proj
      run: ./build_macosx.sh
    - name: build
      run: xcodebuild -project ./proj/picasso.xcodeproj

